import { expect, test } from '@playwright/test'
import { readSnapshot, waitSaved } from './sessionDatabase'
import type { HistoricalSessionSnapshot } from '../../src/storage/historicalSessionSnapshot'

test('指定UTC+8起点与预热不提前交易，重练及本机未见检验保持各自账户和进度', async ({ page }) => {
  const rows = Array.from({ length: 10 }, (_, index) => `${new Date(Date.UTC(2024, 2, 4, 8, index + 1)).toISOString()},1.1,1.1,1.1,1.1,1.1001`)
  const csv = ['timestamp,open,high,low,close,ask', ...rows].join('\n')
  await page.goto('/')
  await waitSaved(page)
  await page.getByLabel('历史数据管理', { exact: true }).locator('summary').click()
  await page.getByLabel('CSV 文件', { exact: true }).setInputFiles({ name: 'generated-start.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) })
  await page.getByRole('button', { name: '导入 CSV', exact: true }).click()
  await expect(page.getByRole('button', { name: '开始历史练习', exact: true })).toBeEnabled()
  await page.getByLabel('开始时间（UTC+8，可留空从首根开始）', { exact: true }).fill('2024-03-04T16:04')
  await page.getByRole('button', { name: '开始历史练习', exact: true }).click()
  await waitSaved(page)
  const first = await readSnapshot<HistoricalSessionSnapshot>(page)
  expect(first.historyStart).toEqual({ version: 1, startFrameIndex: 3, warmupFrameCount: 3 })
  expect(first.frames).toHaveLength(4)
  await expect(page.getByTestId('progress')).toContainText('1 / 7 根')
  await page.getByRole('button', { name: '买涨（做多）', exact: true }).click()
  await waitSaved(page)
  await page.getByRole('button', { name: '下一根', exact: true }).click()
  await waitSaved(page)
  const original = await readSnapshot<HistoricalSessionSnapshot>(page)
  await page.locator('.practice-comparison > summary').click()
  await page.getByRole('button', { name: '重练已见片段', exact: true }).click()
  await waitSaved(page)
  const repeat = await readSnapshot<HistoricalSessionSnapshot>(page)
  expect(repeat.historyStart).toEqual(first.historyStart)
  expect(repeat.sourceState).toEqual(first.sourceState)
  expect(repeat.frames).toEqual(first.frames)
  expect(repeat.account.position).toBeNull()
  expect((await readSnapshot(page, original.id)).account).toEqual(original.account)
  await page.getByRole('button', { name: '本机未见片段检验', exact: true }).click()
  await waitSaved(page)
  const unseen = await readSnapshot<HistoricalSessionSnapshot>(page)
  expect(unseen.sourceState.frameIndex).toBe(5)
  expect(unseen.historyStart?.startFrameIndex).toBe(5)
  await expect(page.getByTestId('progress')).toContainText('1 / 5 根')
  await expect(page.locator('.practice-comparison > summary')).toContainText('本机未见检验')
  await page.getByRole('button', { name: 'H1', exact: true }).click()
  await expect(page.getByTestId('market-chart')).toHaveAttribute('data-last-timestamp', String(Date.UTC(2024, 2, 4, 8, 6)))
  await page.reload()
  await waitSaved(page)
  expect(await readSnapshot(page)).toEqual(unseen)
  await expect(page.locator('.practice-comparison > summary')).toContainText('本机未见检验')
})
