import { expect, test } from '@playwright/test'
import { readSnapshot, waitSaved } from './sessionDatabase'

test('引导可跳过，事前计划、独立复盘、多周期和逐根行情读数形成闭环', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await waitSaved(page)
  const beforeGuide = await readSnapshot(page)
  await page.getByLabel('新手三步引导', { exact: true }).locator('summary').first().click()
  const skipGuide = page.getByRole('button', { name: '跳过引导', exact: true })
  if (await skipGuide.isVisible()) {
    await skipGuide.focus()
    await page.keyboard.press('Enter')
    await expect(skipGuide).toHaveCount(0)
    expect(await readSnapshot(page)).toEqual(beforeGuide)
  }
  await page.locator('.trade-learning > summary').click()
  await page.getByLabel('预览方向', { exact: true }).selectOption('short')
  await page.getByLabel('假设平仓 Ask 报价', { exact: true }).fill('1.10000')
  await expect(page.locator('.risk-readout')).toContainText('每 pip 美元变化')
  await expect(page.locator('.risk-readout')).toContainText('假设平仓结果')
  await page.getByLabel('下单前进场理由（可选）', { exact: true }).fill('只依据当前走势，不使用未来价格')
  await page.getByLabel('计划退出条件（可选）', { exact: true }).fill('推进后主动核对退出报价')
  await page.getByRole('button', { name: '买涨（做多）', exact: true }).click()
  await waitSaved(page)
  await page.getByRole('button', { name: '下一根', exact: true }).click()
  await waitSaved(page)
  await page.getByRole('button', { name: '平仓', exact: true }).click()
  await waitSaved(page)
  const settled = await readSnapshot(page)
  await page.locator('.table-scroll .review-trade-button').first().click()
  await expect(page.getByRole('button', { name: '返回当前行情', exact: true })).toBeVisible()
  expect(await readSnapshot(page)).toEqual(settled)
  await page.locator('.trade-review .original-plan > summary').click()
  await expect(page.locator('.trade-review .original-plan')).toContainText('只依据当前走势，不使用未来价格')
  await page.getByLabel('实际退出说明（可选）', { exact: true }).fill('<script>按计划退出，文本不会执行</script>')
  await page.locator('.trade-review').getByRole('button', { name: '保存备注', exact: true }).click()
  await expect(page.locator('.trade-review')).toContainText('备注已保存到本机。')
  expect(await readSnapshot(page)).toEqual(settled)
  await page.getByRole('button', { name: 'M5', exact: true }).click()
  const chart = page.getByTestId('market-chart')
  await expect(chart).toHaveAttribute('data-timeframe', 'M5')
  await page.getByRole('button', { name: 'M1', exact: true }).click()
  await chart.focus()
  await page.keyboard.press('ArrowUp')
  await expect(page.getByTestId('chart-readout')).toContainText('选中')
  await page.locator('.quote-table-panel > summary').click()
  await expect(page.getByRole('table', { name: 'M1 已发生的报价及 OHLC', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '返回当前行情', exact: true }).click()
  await expect(page.getByRole('button', { name: '返回当前行情', exact: true })).toHaveCount(0)
  expect(await readSnapshot(page)).toEqual(settled)
  await page.locator('.statistics-panel > summary').click()
  await page.getByRole('button', { name: '计算统计', exact: true }).click()
  await expect(page.locator('.statistics-grid')).toContainText('净已结算盈亏')
  await expect(page.locator('.result-distribution')).toContainText('笔')
  await page.screenshot({ path: 'test-results/practice-review.png', fullPage: true })
  expect(errors).toEqual([])
})

test('320px 概念练习与主动观察不产生订单，文字放大后仍可提交', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/')
  await waitSaved(page)
  const before = await readSnapshot(page)
  await page.locator('.concept-practice > summary').click()
  await page.getByRole('radio', { name: 'Bid / Ask 的点差', exact: true }).check()
  await page.getByRole('button', { name: '查看解释', exact: true }).click()
  await expect(page.locator('.concept-feedback')).toContainText('概念判断正确')
  await page.getByRole('button', { name: '另一组核对题 B', exact: true }).click()
  const checkAnswers = ['按 Bid 卖出、Ask 买回的报价差', '不能，计划价并非自动订单或亏损保证', '应分别记录盈利结果和计划偏离', '开仓 Ask 1.25030 仍高于退出 Bid 1.25020']
  for (const [index, answer] of checkAnswers.entries()) {
    await page.getByRole('radio', { name: answer, exact: true }).check()
    await page.getByRole('button', { name: '查看解释', exact: true }).click()
    await expect(page.locator('.concept-feedback')).toContainText('概念判断正确')
    if (index < checkAnswers.length - 1) await page.getByRole('button', { name: '下一题', exact: true }).click()
  }
  await expect(page.locator('.fixed-example')).toContainText('1.25000')
  await expect(page.locator('.fixed-example')).toContainText('亏损 -0.10 USD')
  await page.getByRole('button', { name: '练习题 A', exact: true }).click()
  await expect(page.getByRole('radio', { name: 'Bid / Ask 的点差', exact: true })).not.toBeChecked()
  await page.addStyleTag({ content: 'html { font-size: 32px !important; }' })
  await page.getByRole('button', { name: '记录不交易决定', exact: true }).click()
  await expect(page.locator('.concept-practice')).toContainText('已记录')
  expect((await readSnapshot(page)).trades).toEqual(before.trades)
  expect((await readSnapshot(page)).account).toEqual(before.account)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/practice-concepts-mobile-large-text.png', fullPage: true })
})

test('并发备注拒绝旧版本并保留输入，用户可以明确读取最新版本', async ({ page, context }) => {
  await page.goto('/')
  await waitSaved(page)
  await page.getByRole('button', { name: '买涨（做多）', exact: true }).click()
  await waitSaved(page)
  await page.getByRole('button', { name: '平仓', exact: true }).click()
  await waitSaved(page)
  const other = await context.newPage()
  try {
    await other.goto('/')
    await waitSaved(other)
    for (const target of [page, other]) await target.locator('.table-scroll .review-trade-button').first().click()
    const firstNote = page.getByLabel('实际退出说明（可选）', { exact: true })
    const secondNote = other.getByLabel('实际退出说明（可选）', { exact: true })
    await firstNote.fill('窗口一的已保存说明')
    await secondNote.fill('窗口二尚未保存的说明')
    await page.locator('.trade-review').getByRole('button', { name: '保存备注', exact: true }).click()
    await expect(page.locator('.trade-review')).toContainText('备注已保存到本机。')
    await other.locator('.trade-review').getByRole('button', { name: '保存备注', exact: true }).click()
    await expect(other.locator('.trade-review')).toContainText('另一窗口已修改')
    await expect(other.locator('.annotation-editor p[role="alert"]')).toBeFocused()
    await expect(secondNote).toHaveValue('窗口二尚未保存的说明')
    await other.getByRole('button', { name: '读取保存版本并替换输入', exact: true }).click()
    await expect(secondNote).toHaveValue('窗口一的已保存说明')
    await secondNote.fill('读取最新版本后补充退出原因')
    await other.locator('.trade-review').getByRole('button', { name: '保存备注', exact: true }).click()
    await expect(other.locator('.trade-review')).toContainText('备注已保存到本机。')
  } finally { await other.close() }
})

test('备注长度限制拒绝20k输入且保留Unicode与HTML样式文字，不执行或覆盖已保存备注', async ({ page }) => {
  await page.goto('/')
  await waitSaved(page)
  await page.getByRole('button', { name: '买涨（做多）', exact: true }).click()
  await waitSaved(page)
  await page.getByRole('button', { name: '平仓', exact: true }).click()
  await waitSaved(page)
  await page.locator('.table-scroll .review-trade-button').first().click()
  const note = page.getByLabel('实际退出说明（可选）', { exact: true })
  const payload = '中文 🧠 <script>window.__fxTextExecuted=true</script>'
  await note.fill(payload)
  await page.locator('.trade-review').getByRole('button', { name: '保存备注', exact: true }).click()
  await expect(page.locator('.trade-review')).toContainText('备注已保存到本机。')
  await expect(note).toHaveAttribute('maxlength', '2000')
  const oversized = '界'.repeat(20_000 - payload.length) + payload
  await note.evaluate((element, text) => {
    const textarea = element as HTMLTextAreaElement
    textarea.value = text
    textarea.dispatchEvent(new Event('input', { bubbles: true }))
  }, oversized)
  await expect(note).toHaveValue(oversized)
  await expect(page.locator('.trade-review').getByRole('button', { name: '保存备注', exact: true })).toBeDisabled()
  await note.evaluate(element => element.closest('form')?.dispatchEvent(new Event('submit', { bubbles: true, cancelable: true })))
  await expect(page.locator('.annotation-editor p[role="alert"]')).toBeFocused()
  await page.getByRole('button', { name: '读取保存版本并替换输入', exact: true }).click()
  await expect(note).toHaveValue(payload)
  expect(await page.evaluate(() => Reflect.has(window, '__fxTextExecuted'))).toBe(false)
})
