import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'
import { extendSession, makeSession } from '../unit/sessionFixture'
import type { SessionSnapshot } from '../../src/storage/sessionSnapshot'

async function waitSaved(page: Page) {
  await expect(page.getByTestId('save-status')).toHaveText('已保存到本机')
}

async function restoreProgressedSession(page: Page, frameCount: number) {
  const snapshot = extendSession(makeSession('EUR/USD', 1440), frameCount - 1)
  await page.evaluate(async (savedSnapshot: SessionSnapshot) => {
    const database = await new Promise<IDBDatabase>((resolve, reject) => {
      const request = indexedDB.open('fx-simulation', 1)
      request.onsuccess = () => resolve(request.result)
      request.onerror = () => reject(request.error)
    })
    try {
      await new Promise<void>((resolve, reject) => {
        const transaction = database.transaction(['settings', 'sessions'], 'readwrite')
        transaction.objectStore('sessions').put(savedSnapshot)
        transaction.objectStore('settings').put({ id: savedSnapshot.id, revision: savedSnapshot.revision }, 'current')
        transaction.oncomplete = () => resolve()
        transaction.onabort = () => reject(transaction.error)
      })
    } finally { database.close() }
  }, snapshot)
  await page.reload()
  await waitSaved(page)
}

test('帮助提示可用键盘打开、Escape 关闭并返回焦点', async ({ page }) => {
  await page.goto('/')
  await waitSaved(page)
  const trigger = page.getByRole('button', { name: '点差说明', exact: true })
  await trigger.focus()
  await page.keyboard.press('Enter')
  const panel = page.getByRole('dialog', { name: '点差说明', exact: true })
  await expect(panel).toBeVisible()
  await expect(panel).toBeFocused()
  await expect(panel).toContainText('系统不会重复扣除点差')
  await page.keyboard.press('Escape')
  await expect(panel).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await trigger.click()
  await page.getByRole('button', { name: '关闭说明', exact: true }).click()
  await expect(trigger).toBeFocused()
  await expect(trigger).toHaveAttribute('aria-expanded', 'false')
})

test('图表缩放、观察范围、实际 Ask 标记及类型切换保持同一实例', async ({ page }) => {
  await page.goto('/')
  await waitSaved(page)
  await restoreProgressedSession(page, 240)
  const chart = page.getByTestId('market-chart')
  await expect(chart).toHaveAttribute('data-frame-count', '240')
  const instanceId = await chart.getAttribute('data-chart-instance-id')
  const originalSpan = Number(await chart.getAttribute('data-viewport-to')) - Number(await chart.getAttribute('data-viewport-from'))
  const plotBounds = await chart.boundingBox()
  if (!plotBounds) throw new Error('图表未显示')
  const pointerX = plotBounds.x + plotBounds.width * .5
  const pointerY = plotBounds.y + plotBounds.height * .4
  await page.mouse.move(pointerX, pointerY)
  await page.mouse.wheel(0, -240)
  await expect.poll(async () => Number(await chart.getAttribute('data-viewport-to')) - Number(await chart.getAttribute('data-viewport-from'))).toBeLessThan(originalSpan)
  const zoomedFrom = await chart.getAttribute('data-viewport-from')
  await page.mouse.down()
  await page.mouse.move(pointerX + 70, pointerY, { steps: 8 })
  await page.mouse.up()
  await expect.poll(() => chart.getAttribute('data-viewport-from')).not.toBe(zoomedFrom)
  await chart.focus()
  await page.keyboard.press('+')
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('ArrowLeft')
  const from = await chart.getAttribute('data-viewport-from')
  const to = await chart.getAttribute('data-viewport-to')
  expect(Number(to)).toBeLessThan(239)
  expect(Number(from)).toBeGreaterThanOrEqual(0)
  await page.getByRole('button', { name: '下一根', exact: true }).click()
  await waitSaved(page)
  await expect(chart).toHaveAttribute('data-frame-count', '241')
  await expect(chart).toHaveAttribute('data-viewport-from', from!)
  await expect(chart).toHaveAttribute('data-viewport-to', to!)
  await page.getByRole('button', { name: 'K 线', exact: true }).click()
  await expect(chart).toHaveAttribute('data-chart-instance-id', instanceId!)
  await expect(chart).toHaveAttribute('data-viewport-from', from!)
  await expect(chart).toHaveAttribute('data-viewport-to', to!)
  await page.getByRole('button', { name: '折线', exact: true }).click()
  await chart.focus()
  await page.keyboard.press('End')
  await expect(chart).toHaveAttribute('data-viewport-to', '240')
  await page.getByRole('button', { name: '买涨（做多）', exact: true }).click()
  await waitSaved(page)
  const askPrice = Number(await page.getByTestId('ask-price').textContent())
  await expect(chart).toHaveAttribute('data-marker-count', '1')
  expect(Number(await chart.getAttribute('data-price-max'))).toBeGreaterThanOrEqual(askPrice)
  const bounds = await chart.boundingBox()
  if (!bounds) throw new Error('图表未显示')
  await page.mouse.move(bounds.x + bounds.width * .65, bounds.y + bounds.height * .45)
  await expect(page.getByTestId('chart-readout')).toContainText('UTC+8')
  await expect(page.getByTestId('chart-readout')).toContainText('十字线')
  await page.screenshot({ path: 'test-results/chart-crosshair.png', fullPage: true })
  await page.setViewportSize({ width: 1024, height: 900 })
  await expect(chart).toHaveAttribute('data-chart-instance-id', instanceId!)
  await page.getByRole('button', { name: '平仓', exact: true }).click()
  await waitSaved(page)
  await expect(chart).toHaveAttribute('data-marker-count', '2')
  expect((await chart.getAttribute('data-marker-prices'))?.split(',').map(Number)).toContain(askPrice)
})

for (const width of [1440, 1024, 390]) {
  test(`${width}px 初始、播放、持仓和成交视觉状态及200%文字`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/')
    await waitSaved(page)
    await expect(page.getByTestId('market-chart')).toHaveAttribute('data-frame-count', '1')
    await page.screenshot({ path: `test-results/design-${width}-initial.png`, fullPage: true })
    await restoreProgressedSession(page, 360)
    await page.getByLabel('速度').selectOption('10')
    await page.getByRole('button', { name: '播放', exact: true }).click()
    await expect(page.getByTestId('progress')).toContainText('370 / 1440')
    await page.screenshot({ path: `test-results/design-${width}-playing.png`, fullPage: true })
    await page.getByRole('button', { name: '暂停', exact: true }).click()
    await waitSaved(page)
    await page.getByRole('button', { name: '买涨（做多）', exact: true }).click()
    await waitSaved(page)
    if (width === 1440) {
      await page.evaluate(() => scrollTo(0, 0))
      const closeBounds = await page.getByRole('button', { name: '平仓', exact: true }).boundingBox()
      const playBounds = await page.getByRole('button', { name: '播放', exact: true }).boundingBox()
      expect(closeBounds!.y + closeBounds!.height).toBeLessThanOrEqual(900)
      expect(playBounds!.y + playBounds!.height).toBeLessThanOrEqual(900)
    }
    await page.screenshot({ path: `test-results/design-${width}-position.png`, fullPage: true })
    await page.getByRole('button', { name: '下一根', exact: true }).click()
    await waitSaved(page)
    await page.getByRole('button', { name: '平仓', exact: true }).click()
    await waitSaved(page)
    await page.screenshot({ path: `test-results/design-${width}-trades.png`, fullPage: true })
    if (width === 390) {
      await page.locator('.mobile-trade summary').focus()
      await page.keyboard.press('Enter')
      await expect(page.locator('.mobile-trade')).toHaveAttribute('open', '')
      await expect(page.locator('.mobile-trades').getByText('开仓价', { exact: true })).toBeVisible()
    }
    await page.addStyleTag({ content: 'html { font-size: 32px !important; }' })
    await expect(page.getByLabel('交易金额（USD）')).toHaveCSS('font-size', '40px')
    await page.getByRole('button', { name: '买跌（做空）', exact: true }).focus()
    await page.keyboard.press('Enter')
    await waitSaved(page)
    await expect(page.getByRole('button', { name: '平仓', exact: true })).toBeEnabled()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `test-results/design-${width}-large-text.png`, fullPage: true })
  })
}

test('最高回放速度完成1440根，界面可操作且运行资源均来自本机', async ({ page }, testInfo) => {
  test.setTimeout(210_000)
  const requests: string[] = []
  const errors: string[] = []
  page.on('request', request => requests.push(request.url()))
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await waitSaved(page)
  const chart = page.getByTestId('market-chart')
  const instanceId = await chart.getAttribute('data-chart-instance-id')
  await page.getByLabel('速度').selectOption('10')
  const startedAt = Date.now()
  await page.getByRole('button', { name: '播放', exact: true }).click()
  await expect(page.getByTestId('progress')).toContainText('101 / 1440', { timeout: 20_000 })
  const interactionStartedAt = Date.now()
  await page.getByRole('button', { name: 'K 线', exact: true }).click()
  await expect(page.getByRole('button', { name: 'K 线', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '点差说明', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '点差说明', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  const interactionMs = Date.now() - interactionStartedAt
  expect(interactionMs).toBeLessThan(2000)
  await expect(page.getByTestId('progress')).toContainText('1440 / 1440 根 · 已结束', { timeout: 180_000 })
  await waitSaved(page)
  await expect(chart).toHaveAttribute('data-chart-instance-id', instanceId!)
  await expect(chart).toHaveAttribute('data-frame-count', '1440')
  await expect(page.getByRole('button', { name: '播放', exact: true })).toBeDisabled()
  expect(errors).toEqual([])
  expect(requests.filter(url => new URL(url).origin !== 'http://127.0.0.1:4173')).toEqual([])
  await expect(page.locator('body')).not.toContainText(/TradingView|Lightweight Charts|Copyright|Apache ECharts/)
  await expect(page.locator('a[href^="http"]')).toHaveCount(0)
  await page.screenshot({ path: 'test-results/design-complete-1440.png', fullPage: true })
  await testInfo.attach('回放与交互耗时', { body: JSON.stringify({ replayMs: Date.now() - startedAt, interactionMs, frameCount: 1440, instanceId }), contentType: 'application/json' })
})
