import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'
import { closePosition, openPosition } from '../../src/engine/execution'
import { advanceSimulation } from '../../src/engine/simulationSource'
import { extendSession, makeSession } from '../unit/sessionFixture'
import { readHistoryChunks, readSnapshot, waitSaved, writeSnapshot } from './sessionDatabase'

async function restoreProgressedSession(page: Page, frameCount: number) {
  const snapshot = extendSession(makeSession('EUR/USD', null), frameCount - 1)
  await writeSnapshot(page, snapshot)
  await page.reload()
  await waitSaved(page)
}

test('窄屏交易入口与开平仓保持键盘焦点，记录锚点可到达', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 900 })
  await page.goto('/')
  await waitSaved(page)
  const amountInput = page.getByLabel('交易金额（USD）')
  await page.getByRole('link', { name: '去下单', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(amountInput).toBeFocused()
  await amountInput.fill('500')
  await page.getByRole('button', { name: '买涨（做多）', exact: true }).focus()
  await page.keyboard.press('Enter')
  await waitSaved(page)
  await expect(page.locator('#position-title')).toBeFocused()
  await expect(page.getByText('当前已有持仓，请先平仓。', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: '查看持仓与平仓', exact: true }).click()
  await expect(page.locator('#position-title')).toBeFocused()
  await page.getByRole('button', { name: '平仓', exact: true }).click()
  await waitSaved(page)
  await expect(amountInput).toBeFocused()
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.getByRole('link', { name: '成交记录', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('#trade-journal')).toBeFocused()
  await expect(page.locator('.table-scroll table')).toBeVisible()
})

test('帮助提示可用键盘打开、Escape 关闭并返回焦点', async ({ page }) => {
  await page.goto('/')
  await waitSaved(page)
  const trigger = page.getByRole('button', { name: '点差说明', exact: true })
  await trigger.focus()
  await page.keyboard.press('Enter')
  const panel = page.getByRole('dialog', { name: '点差说明', exact: true })
  await expect(panel).toBeVisible()
  await expect(panel).toBeFocused()
  await expect(panel).toContainText('系统不会重复扣除点差')
  await page.keyboard.press('Escape')
  await expect(panel).toHaveCount(0)
  await expect(trigger).toBeFocused()
  await trigger.click()
  await page.getByRole('button', { name: '关闭说明', exact: true }).click()
  await expect(trigger).toBeFocused()
  await expect(trigger).toHaveAttribute('aria-expanded', 'false')
})

test('图表缩放、观察范围、实际 Ask 标记及类型切换保持同一实例', async ({ page }) => {
  await page.goto('/')
  await waitSaved(page)
  await restoreProgressedSession(page, 240)
  const chart = page.getByTestId('market-chart')
  await expect(chart).toHaveAttribute('data-frame-count', '240')
  const instanceId = await chart.getAttribute('data-chart-instance-id')
  const originalSpan = Number(await chart.getAttribute('data-viewport-to')) - Number(await chart.getAttribute('data-viewport-from'))
  const plotBounds = await chart.boundingBox()
  if (!plotBounds) throw new Error('图表未显示')
  const pointerX = plotBounds.x + plotBounds.width * .5
  const pointerY = plotBounds.y + plotBounds.height * .4
  await page.mouse.move(pointerX, pointerY)
  await page.mouse.wheel(0, -240)
  await expect.poll(async () => Number(await chart.getAttribute('data-viewport-to')) - Number(await chart.getAttribute('data-viewport-from'))).toBeLessThan(originalSpan)
  const zoomedFrom = await chart.getAttribute('data-viewport-from')
  await page.mouse.down()
  await page.mouse.move(pointerX + 70, pointerY, { steps: 8 })
  await page.mouse.up()
  await expect.poll(() => chart.getAttribute('data-viewport-from')).not.toBe(zoomedFrom)
  await chart.focus()
  await page.keyboard.press('+')
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('ArrowLeft')
  const from = await chart.getAttribute('data-viewport-from')
  const to = await chart.getAttribute('data-viewport-to')
  expect(Number(to)).toBeLessThan(239)
  expect(Number(from)).toBeGreaterThanOrEqual(0)
  await page.getByRole('button', { name: '下一根', exact: true }).click()
  await waitSaved(page)
  await expect(chart).toHaveAttribute('data-frame-count', '241')
  await expect(chart).toHaveAttribute('data-viewport-from', from!)
  await expect(chart).toHaveAttribute('data-viewport-to', to!)
  await page.getByRole('button', { name: 'K 线', exact: true }).click()
  await expect(chart).toHaveAttribute('data-chart-instance-id', instanceId!)
  await expect(chart).toHaveAttribute('data-viewport-from', from!)
  await expect(chart).toHaveAttribute('data-viewport-to', to!)
  await page.getByRole('button', { name: '折线', exact: true }).click()
  await chart.focus()
  await page.keyboard.press('End')
  await expect(chart).toHaveAttribute('data-viewport-to', '240')
  await page.getByRole('button', { name: '买涨（做多）', exact: true }).click()
  await waitSaved(page)
  const askPrice = Number(await page.getByTestId('ask-price').textContent())
  await expect(chart).toHaveAttribute('data-marker-count', '1')
  expect(Number(await chart.getAttribute('data-price-max'))).toBeGreaterThanOrEqual(askPrice)
  const bounds = await chart.boundingBox()
  if (!bounds) throw new Error('图表未显示')
  await page.mouse.move(bounds.x + bounds.width * .65, bounds.y + bounds.height * .45)
  await expect(page.getByTestId('chart-readout')).toContainText('UTC+8')
  await expect(page.getByTestId('chart-readout')).toContainText('十字线')
  await page.screenshot({ path: 'test-results/chart-crosshair.png', fullPage: true })
  await page.setViewportSize({ width: 1024, height: 900 })
  await expect(chart).toHaveAttribute('data-chart-instance-id', instanceId!)
  await page.getByRole('button', { name: '平仓', exact: true }).click()
  await waitSaved(page)
  await expect(chart).toHaveAttribute('data-marker-count', '2')
  expect((await chart.getAttribute('data-marker-prices'))?.split(',').map(Number)).toContain(askPrice)
})

for (const width of [1440, 1024, 390]) {
  test(`${width}px 初始、播放、持仓和成交视觉状态及200%文字`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/')
    await waitSaved(page)
    await expect(page.getByTestId('market-chart')).toHaveAttribute('data-frame-count', '1')
    await page.screenshot({ path: `test-results/design-${width}-initial.png`, fullPage: true })
    await restoreProgressedSession(page, 360)
    await page.getByLabel('速度').selectOption('10')
    await page.getByRole('button', { name: '播放', exact: true }).click()
    await expect.poll(async () => Number(await page.getByTestId('market-chart').getAttribute('data-frame-count'))).toBeGreaterThanOrEqual(370)
    await page.screenshot({ path: `test-results/design-${width}-playing.png`, fullPage: true })
    await page.getByRole('button', { name: '暂停', exact: true }).click()
    await waitSaved(page)
    await page.getByRole('button', { name: '买涨（做多）', exact: true }).click()
    await waitSaved(page)
    if (width === 1440) {
      await page.evaluate(() => scrollTo(0, 0))
      const closeBounds = await page.getByRole('button', { name: '平仓', exact: true }).boundingBox()
      const playBounds = await page.getByRole('button', { name: '播放', exact: true }).boundingBox()
      expect(closeBounds!.y + closeBounds!.height).toBeLessThanOrEqual(900)
      expect(playBounds!.y + playBounds!.height).toBeLessThanOrEqual(900)
    }
    await page.screenshot({ path: `test-results/design-${width}-position.png`, fullPage: true })
    await page.getByRole('button', { name: '下一根', exact: true }).click()
    await waitSaved(page)
    await page.getByRole('button', { name: '平仓', exact: true }).click()
    await waitSaved(page)
    await page.screenshot({ path: `test-results/design-${width}-trades.png`, fullPage: true })
    if (width === 390) {
      await page.locator('.mobile-trade summary').focus()
      await page.keyboard.press('Enter')
      await expect(page.locator('.mobile-trade')).toHaveAttribute('open', '')
      await expect(page.locator('.mobile-trades').getByText('开仓价', { exact: true })).toBeVisible()
    }
    await page.addStyleTag({ content: 'html { font-size: 32px !important; }' })
    await expect(page.getByLabel('交易金额（USD）')).toHaveCSS('font-size', '40px')
    await page.getByRole('button', { name: '买跌（做空）', exact: true }).focus()
    await page.keyboard.press('Enter')
    await waitSaved(page)
    await expect(page.getByRole('button', { name: '平仓', exact: true })).toBeEnabled()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: `test-results/design-${width}-large-text.png`, fullPage: true })
  })
}

test('持续播放超过1440根后手动暂停，保留全部历史并刷新继续原练习', async ({ page }, testInfo) => {
  test.setTimeout(240_000)
  const requests: string[] = []
  const errors: string[] = []
  page.on('request', request => requests.push(request.url()))
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await waitSaved(page)
  const initial = await readSnapshot(page)
  expect(initial.sourceState.maxFrames).toBeNull()
  const chart = page.getByTestId('market-chart')
  const instanceId = await chart.getAttribute('data-chart-instance-id')
  await page.getByLabel('速度').selectOption('10')
  const startedAt = Date.now()
  await page.getByRole('button', { name: '播放', exact: true }).click()
  await expect.poll(async () => Number(await chart.getAttribute('data-frame-count')), { timeout: 20_000 }).toBeGreaterThanOrEqual(101)
  const interactionStartedAt = Date.now()
  await page.getByRole('button', { name: 'K 线', exact: true }).click()
  await expect(page.getByRole('button', { name: 'K 线', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '点差说明', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '点差说明', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  const interactionMs = Date.now() - interactionStartedAt
  expect(interactionMs).toBeLessThan(2000)
  await expect.poll(async () => {
    const progress = await page.getByTestId('progress').textContent()
    return Number(progress?.match(/已推进 (\d+) 根/)?.[1] ?? 0)
  }, { timeout: 180_000, intervals: [1000] }).toBeGreaterThanOrEqual(1501)
  await expect(page.getByTestId('progress')).toContainText('播放中')
  await page.getByRole('button', { name: '暂停', exact: true }).focus()
  await page.keyboard.press('Enter')
  await waitSaved(page)
  const paused = await readSnapshot(page)
  const frameCount = paused.sourceState.frameIndex + 1
  expect(frameCount).toBeGreaterThan(1440)
  expect(paused.frames).toHaveLength(1440)
  expect(paused.frameStartIndex).toBe(frameCount - 1440)
  expect(paused.sourceState.seed).toBe(initial.sourceState.seed)
  await expect(page.getByTestId('progress')).toContainText(`已推进 ${frameCount} 根 · 已暂停`)
  await expect(chart).toHaveAttribute('data-chart-instance-id', instanceId!)
  await expect(chart).toHaveAttribute('data-frame-count', '1440')
  await expect(chart).toHaveAttribute('data-first-timestamp', String(paused.frames[0]!.quote.timestampMs))
  await expect(chart).toHaveAttribute('data-last-timestamp', String(paused.sourceState.currentTimestampMs))
  await expect(page.getByRole('button', { name: '播放', exact: true })).toBeEnabled()
  await expect(page.getByRole('button', { name: '下一根', exact: true })).toBeEnabled()
  const chunks = await readHistoryChunks(page, paused.id)
  expect(chunks).toHaveLength(Math.ceil(frameCount / 1440))
  expect(chunks.map(chunk => chunk.chunkIndex)).toEqual(chunks.map((_, index) => index))
  expect(chunks.slice(0, -1).every(chunk => chunk.frames.length === 1440)).toBe(true)
  const history = chunks.flatMap(chunk => chunk.frames)
  expect(history).toHaveLength(frameCount)
  expect(history[0]).toEqual(initial.frames[0])
  expect(history.slice(paused.frameStartIndex)).toEqual(paused.frames)
  expect(history.every((frame, index) => index === 0 || frame.quote.timestampMs > history[index - 1]!.quote.timestampMs)).toBe(true)
  await page.waitForTimeout(700)
  expect(await readSnapshot(page)).toEqual(paused)
  await page.screenshot({ path: 'test-results/design-continuous-over-1440.png', fullPage: true })
  await page.reload()
  await waitSaved(page)
  expect(await readSnapshot(page)).toEqual(paused)
  await expect(page.getByTestId('progress')).toContainText(`已推进 ${frameCount} 根 · 已暂停`)
  const expectedNext = advanceSimulation(paused.sourceState)!
  await page.getByRole('button', { name: '下一根', exact: true }).click()
  await waitSaved(page)
  const continued = await readSnapshot(page)
  expect(continued.sourceState).toEqual(expectedNext.state)
  expect(continued.frames.at(-1)).toEqual(expectedNext.frame)
  expect(continued.id).toBe(paused.id)
  expect(continued.frameStartIndex).toBe(paused.frameStartIndex + 1)
  expect((await readHistoryChunks(page, continued.id)).flatMap(chunk => chunk.frames)).toEqual([...history, expectedNext.frame])
  expect(errors).toEqual([])
  expect(requests.filter(url => new URL(url).origin !== 'http://127.0.0.1:4173')).toEqual([])
  await expect(page.locator('body')).not.toContainText(/TradingView|Lightweight Charts|Copyright|Apache ECharts/)
  await expect(page.locator('a[href^="http"]')).toHaveCount(0)
  await testInfo.attach('持续行情与交互耗时', { body: JSON.stringify({ replayMs: Date.now() - startedAt, interactionMs, frameCount, chartFrameCount: paused.frames.length, archivedFrameCount: history.length, instanceId }), contentType: 'application/json' })
})

test('行情移出最近窗口时保留仍在窗口内的观察时间，过旧范围贴近保留边界', async ({ page }) => {
  await page.goto('/')
  await waitSaved(page)
  await restoreProgressedSession(page, 1440)
  const chart = page.getByTestId('market-chart')
  const instanceId = await chart.getAttribute('data-chart-instance-id')
  const firstTimestamp = await chart.getAttribute('data-first-timestamp')
  await chart.focus()
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('ArrowLeft')
  const startTime = await chart.getAttribute('data-viewport-start-time')
  const endTime = await chart.getAttribute('data-viewport-end-time')
  await page.getByRole('button', { name: '下一根', exact: true }).click()
  await waitSaved(page)
  await expect(chart).toHaveAttribute('data-frame-count', '1440')
  await expect(chart).toHaveAttribute('data-viewport-start-time', startTime!)
  await expect(chart).toHaveAttribute('data-viewport-end-time', endTime!)
  await expect(chart).toHaveAttribute('data-chart-instance-id', instanceId!)
  await page.getByRole('button', { name: 'K 线', exact: true }).click()
  await expect(chart).toHaveAttribute('data-viewport-start-time', startTime!)
  await expect(chart).toHaveAttribute('data-viewport-end-time', endTime!)
  await chart.focus()
  for (let step = 0; step < 100 && Number(await chart.getAttribute('data-viewport-from')) > 0; step += 1) {
    await page.keyboard.press('ArrowLeft')
  }
  await expect(chart).toHaveAttribute('data-viewport-from', '0')
  await page.getByRole('button', { name: '下一根', exact: true }).click()
  await waitSaved(page)
  await expect(chart).toHaveAttribute('data-viewport-from', '0')
  const snapshot = await readSnapshot(page)
  await expect(chart).toHaveAttribute('data-viewport-start-time', String(snapshot.frames[0]!.quote.timestampMs))
  expect(await chart.getAttribute('data-first-timestamp')).not.toBe(firstTimestamp)
  await chart.focus()
  await page.keyboard.press('End')
  await expect(chart).toHaveAttribute('data-viewport-end-time', String(snapshot.sourceState.currentTimestampMs))
  await expect(chart).toHaveAttribute('data-chart-instance-id', instanceId!)
  const history = (await readHistoryChunks(page, snapshot.id)).flatMap(chunk => chunk.frames)
  expect(String(history[0]!.quote.timestampMs)).toBe(firstTimestamp)
  expect(history).toHaveLength(1442)
})

test('成交记录分页保留全部记录，桌面及窄屏可以用键盘查看最早交易', async ({ page }) => {
  const snapshot = makeSession('EUR/USD', null)
  const quote = snapshot.frames[0]!.quote
  for (let index = 1; index <= 45; index += 1) {
    const opened = openPosition(snapshot.account, quote, snapshot.pair, index % 2 ? 'long' : 'short', String(100 + index), `journal-trade-${index}`)
    const closed = closePosition(opened, quote)
    snapshot.account = closed.account
    snapshot.trades.push(closed.trade)
  }
  await page.goto('/')
  await waitSaved(page)
  await writeSnapshot(page, snapshot)
  await page.reload()
  await waitSaved(page)
  const journal = page.locator('#trade-journal')
  const pagination = page.getByRole('navigation', { name: '成交记录分页', exact: true })
  await expect(journal.locator('.trade-count')).toHaveText('45')
  await expect(journal.locator('tbody tr')).toHaveCount(20)
  await expect(journal.locator('tbody tr').first()).toContainText('145.00')
  await expect(pagination.getByRole('status')).toHaveText('第 1 / 3 页')
  await expect(pagination.getByRole('button', { name: '上一页', exact: true })).toBeDisabled()
  const nextPage = pagination.getByRole('button', { name: '下一页', exact: true })
  await nextPage.focus()
  await page.keyboard.press('Enter')
  await expect(pagination.getByRole('status')).toHaveText('第 2 / 3 页')
  await expect(journal.locator('tbody tr')).toHaveCount(20)
  await expect(journal.locator('tbody tr').first()).toContainText('125.00')
  await page.setViewportSize({ width: 390, height: 900 })
  await nextPage.focus()
  await page.keyboard.press('Enter')
  await expect(pagination.getByRole('status')).toHaveText('第 3 / 3 页')
  await expect(journal.locator('.mobile-trade')).toHaveCount(5)
  await expect(nextPage).toBeDisabled()
  const oldest = journal.locator('.mobile-trade').last()
  await expect(oldest.locator('summary')).toContainText('101.00')
  await oldest.locator('summary').focus()
  await page.keyboard.press('Enter')
  await expect(oldest).toHaveAttribute('open', '')
  await expect(oldest.getByText('开仓价', { exact: true })).toBeVisible()
  await page.addStyleTag({ content: 'html { font-size: 32px !important; }' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await pagination.getByRole('button', { name: '上一页', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(pagination.getByRole('status')).toHaveText('第 2 / 3 页')
  expect(await readSnapshot(page)).toEqual(snapshot)
  await page.reload()
  await waitSaved(page)
  await expect(pagination.getByRole('status')).toHaveText('第 1 / 3 页')
  expect((await readSnapshot(page)).trades).toHaveLength(45)
})
